In [22]:
import numpy as np
import pandas as pd
import seaborn as sns
import xgboost as xgb

In [24]:
from sklearn.metrics import accuracy_score

In [26]:
data=pd.read_csv(r"C:\Users\Lenovo\Documents\Notes\APRIL\22nd- Cross validation\Wholesale customers data.csv")
data.head()

   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

In [28]:
x=data.drop(['Channel'],axis=1)

In [30]:
y=data['Channel']

In [32]:
x.head()

   Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0       3  12669  9656     7561     214              2674        1338
1       3   7057  9810     9568    1762              3293        1776
2       3   6353  8808     7684    2405              3516        7844
3       3  13265  1196     4221    6404               507        1788
4       3  22615  5410     7198    3915              1777        5185

In [34]:
y.head()

0    2
1    2
2    2
3    1
4    2
Name: Channel, dtype: int64

In [36]:
y[y==2]=0
y[y==1]=1

In [38]:
y.head()

0    0
1    0
2    0
3    1
4    0
Name: Channel, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [42]:
pip install hyperopt

Requirement already satisfied: hyperopt in c:\users\lenovo\anaconda3\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (1.26.4)
Requirement already satisfied: scipy in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (1.13.1)
Requirement already satisfied: six in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (1.16.0)
Requirement already satisfied: networkx>=2.2 in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (3.3)
Requirement already satisfied: future in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (4.66.5)
Requirement already satisfied: cloudpickle in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (3.0.0)
Requirement already satisfied: py4j in c:\users\lenovo\anaconda3\lib\site-packages (from hyperopt) (0.10.9.9)
Requirement already satisfied: colorama in c:\users\lenovo\anaconda3\lib\site-packages (from tqdm->hyperopt) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [43]:
from hyperopt import hp

In [ ]:
space={'max_depth': hp.quniform("max_depth", 3, 18, 1),
        'gamma': hp.uniform ('gamma', 1,9),
        'reg_alpha' : hp.quniform('reg_alpha', 40,180,1),
        'reg_lambda' : hp.uniform('reg_lambda', 0,1),
        'colsample_bytree' : hp.uniform('colsample_bytree', 0.5,1),
        'min_child_weight' : hp.quniform('min_child_weight', 0, 10, 1),
        'n_estimators': 180,
        'seed': 0
    }

In [ ]:
def objective(space):
    clf=xgb.XGBClassifier(
                    n_estimators =space['n_estimators'], max_depth = int(space['max_depth']), gamma = space['gamma'],
                    reg_alpha = int(space['reg_alpha']),min_child_weight=int(space['min_child_weight']),
                    colsample_bytree=int(space['colsample_bytree']))
    
    evaluation = [( x_train, y_train), ( x_test, y_test)]
    
    clf.fit(x_train, y_train,
            eval_set=evaluation, eval_metric="auc",
            early_stopping_rounds=10,verbose=False)
    

    pred = clf.predict(x_test)
    accuracy = accuracy_score(y_test, pred>0.5)
    print ("SCORE:", accuracy)
    return {'loss': -accuracy, 'status': STATUS_OK }

In [ ]:
pip install --upgrade xgboost

In [ ]:
pip install trails

In [ ]:
from hyperopt import fmin, tpe, hp, Trials

In [ ]:
from hyperopt import Trials

In [63]:
trials = Trials()

best_hyperparams = fmin(fn = objective,space = space,algo = tpe.suggest,
                        max_evals = 100,trials = trials)

  0%|                                                                          | 0/100 [00:00<?, ?trial/s, best loss=?]

job exception: XGBClassifier.fit() got an unexpected keyword argument 'eval_metric'

  0%|                                                                          | 0/100 [00:00<?, ?trial/s, best loss=?]

TypeError: XGBClassifier.fit() got an unexpected keyword argument 'eval_metric'

In [ ]:
print("The best hyperparameters are : ","\n")
print(best_hyperparams)